spring:
  datasource:
    url: ${DB_DSN:jdbc:postgresql://localhost:5432/ah_jsb_auth}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:B4z1n9a!}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  docker:
    compose:
      lifecycle-management: start-only
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      CustomerEmailUnique: CUSTOMER_EMAIL_UNIQUE
      CustomerPhoneUnique: CUSTOMER_PHONE_UNIQUE
      MerchantEmailUnique: MERCHANT_EMAIL_UNIQUE
      MerchantPhoneUnique: MERCHANT_PHONE_UNIQUE
      MerchantNidUnique: MERCHANT_NID_UNIQUE
      AdminEmailUnique: ADMIN_EMAIL_UNIQUE
      AdminPhoneUnique: ADMIN_PHONE_UNIQUE
      AdminNidUnique: ADMIN_NID_UNIQUE
      SysAdminEmailUnique: SYS_ADMIN_EMAIL_UNIQUE
      SysAdminPhoneUnique: SYS_ADMIN_PHONE_UNIQUE
      SysAdminNidUnique: SYS_ADMIN_NID_UNIQUE
      AddressLabelUnique: ADDRESS_LABEL_UNIQUE
springdoc:
  pathsToMatch: /api/**
server:
  port: ${PORT:8080}
